### ISSUE TITLE
cant run launch.json

### ISSUE THREAD

**Issue by matiarj** [jarthursquiers/FireByArthurTradingEngine#1]
when i open launch.json in visual studio there is not option to run the script if i continue along w/ the other instructions when i name my tastyworks csv j.csv it gives me 

ReferenceError: "FireByArthurTradingEngine" is not defined. (line 2, file "Code")

**Comment by jarthursquiers** [comment]
matiarj,

If you are in Visual Studio Code, you shouldn't have to open launch.json itself. You should be able to just hit ctrl+F5 (run without debugging) and the unit tests will run. None of the visual components will run without it being deployed to a Google Sheet.

It also sounds like the engine is not imported correctly in the Google Sheet:

![capture](https://user-images.githubusercontent.com/7815629/48850168-a75e6680-ed6d-11e8-8147-1eb780fe8743.JPG)

**Comment by interconnsys** [comment]
Hi,

I'm getting this error when running the launch.json in VS. I have checked all required packages and they are all installed and updated. Do you have any idea about what I am missing?  Any help is highly appreciated 
Thanks in advance
George

/usr/local/bin/node -r ts-node/register local/local-unittest-bootstrap.ts
/Users/george/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
source-map-support.js:722
TSError: ⨯ Unable to compile TypeScript:
src/bootstraps/testing-engine.ts(33,38): error TS2304: Cannot find name 'Logger'.
src/bootstraps/testing-engine.ts(129,17): error TS2304: Cannot find name 'SpreadsheetApp'.

    at createTSError (/Users/george/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/george/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/george/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/george/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/george/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/george/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  diagnosticCodes: [ 2304, 2304 ]
}
source-map-support.js:726
Process exited with code 1
